# Generated by Django 3.2.3 on 2021-05-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0006_auto_20210516_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
    ]
