# Generated by Django 3.2.3 on 2021-05-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_auto_20210516_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(to='book_store.Country'),
        ),
    ]
